"""v1.0

Revision ID: 908e40e2a58d
Revises: eee08123f53b
Create Date: 2023-01-10 11:58:42.021250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '908e40e2a58d'
down_revision = 'eee08123f53b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
