"""v_1_2

Revision ID: 38c11f45ab9d
Revises: b0d1ad4eabbe
Create Date: 2022-09-21 10:00:07.535524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38c11f45ab9d'
down_revision = 'b0d1ad4eabbe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('createdAt', sa.DateTime(), nullable=True))
    op.drop_column('products', 'createAt')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('createAt', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('products', 'createdAt')
    # ### end Alembic commands ###
