"""modify datatype column createAt

Revision ID: 5280dc9fba25
Revises: 4ac970661225
Create Date: 2022-09-21 09:51:38.312852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5280dc9fba25'
down_revision = '4ac970661225'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
