"""v_1_1

Revision ID: b0d1ad4eabbe
Revises: 5280dc9fba25
Create Date: 2022-09-21 09:57:09.344795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0d1ad4eabbe'
down_revision = '5280dc9fba25'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
